site_name: NodeBB Documentation
theme: yeti
markdown_extensions:
    - fenced_code
    - tables
pages:
    - 'index.md'
    - Installation:
        - via OS:
            - 'installing/os/index.md'
            - 'Arch Linux': 'installing/os/arch.md'
            - 'CentOS': 'installing/os/centos.md'
            - 'installing/os/debian.md'
            - 'FreeBSD/OpenBSD': 'installing/os/freebsd.md'
            - 'OSX': 'installing/os/osx-mavericks.md'
            - 'SmartOS': 'installing/os/smartos.md'
            - 'Ubuntu Linux': 'installing/os/ubuntu.md'
            - 'Windows 8': 'installing/os/windows8.md'
        - via the Cloud:
            - 'installing/cloud/index.md'
            - 'installing/cloud/cloud9.md'
            - 'installing/cloud/cloudron.md'
            - 'installing/cloud/heroku.md'
            - 'installing/cloud/koding.md'
            - 'installing/cloud/nitrous.md'
            - 'installing/cloud/openshift.md'
